// Theme colors
export const theme = {
  primary: '#4A154B',
  primaryLight: '#6B2D6C',
  secondary: '#E5007D',
  tertiary: '#00A3E0',
  success: '#00875A',
  warning: '#F5A623',
  danger: '#DE350B',
};

// Mock opportunities data with all 14 fields
export const opportunities = [
  { 
    id: 'OPP-2024-001', 
    code: 'OPP-001',
    name: 'Digital Transformation Initiative', 
    client: 'Acme Corp', 
    enquiryOwner: 'John Smith',
    expectedFee: 850000,
    expectedFeeINR: 70550000,
    industry: 'Technology', 
    market: 'Commercial',
    subMarket: 'Software',
    keyAccount: 'Yes',
    solution: 'Digital Advisory', 
    legalEntity: 'Grant Thornton India LLP',
    status: 'In Progress',
    billingCurrency: 'USD',
    amount: 850000,
    phase: 'Negotiation',
    solutions: [
      { name: 'Digital Advisory', isPrimary: true, lead: '' },
      { name: 'Technology Consulting', isPrimary: false, lead: '' },
      { name: 'Process Automation', isPrimary: false, lead: '' }
    ],
  },
  { 
    id: 'OPP-2024-002', 
    code: 'OPP-002',
    name: 'Financial Audit FY2024', 
    client: 'Global Industries', 
    enquiryOwner: 'Sarah Johnson',
    expectedFee: 1200000,
    expectedFeeINR: 99600000,
    industry: 'Manufacturing', 
    market: 'Industrial',
    subMarket: 'Heavy Equipment',
    keyAccount: 'Yes',
    solution: 'Audit & Assurance', 
    legalEntity: 'Grant Thornton India LLP',
    status: 'Approved',
    billingCurrency: 'USD',
    amount: 1200000,
    phase: 'Qualification',
  },
  { 
    id: 'OPP-2024-003', 
    code: 'OPP-003',
    name: 'Tax Advisory Services', 
    client: 'TechStart Inc', 
    enquiryOwner: 'Michael Chen',
    expectedFee: 450000,
    expectedFeeINR: 37350000,
    industry: 'Technology', 
    market: 'Commercial',
    subMarket: 'IT Services',
    keyAccount: 'No',
    solution: 'Tax Services', 
    legalEntity: 'Grant Thornton India LLP',
    status: 'Pending',
    billingCurrency: 'USD',
    amount: 450000,
    phase: 'Proposal',
  },
  { 
    id: 'OPP-2024-004', 
    code: 'OPP-004',
    name: 'Risk Management Consulting', 
    client: 'Finance Corp', 
    enquiryOwner: 'David Lee',
    expectedFee: 680000,
    expectedFeeINR: 56440000,
    industry: 'Financial Services', 
    market: 'Banking',
    subMarket: 'Corporate Banking',
    keyAccount: 'Yes',
    solution: 'Risk Advisory', 
    legalEntity: 'Grant Thornton India LLP',
    status: 'In Progress',
    billingCurrency: 'USD',
    amount: 680000,
    phase: 'Negotiation',
  },
  { 
    id: 'OPP-2024-005', 
    code: 'OPP-005',
    name: 'ESG Compliance Assessment', 
    client: 'Green Industries Ltd', 
    enquiryOwner: 'Emily Brown',
    expectedFee: 320000,
    expectedFeeINR: 26560000,
    industry: 'Energy', 
    market: 'Renewable Energy',
    subMarket: 'Solar Power',
    keyAccount: 'No',
    solution: 'ESG Advisory', 
    legalEntity: 'Grant Thornton India LLP',
    status: 'Pending',
    billingCurrency: 'USD',
    amount: 320000,
    phase: 'Discovery',
  },
];

// Grades/Levels
export const grades = [
  { id: 1, name: 'Partner', level: 'P' },
  { id: 2, name: 'Director', level: 'D' },
  { id: 3, name: 'Senior Manager', level: 'SM' },
  { id: 4, name: 'Manager', level: 'M' },
  { id: 5, name: 'Senior Consultant', level: 'SC' },
  { id: 6, name: 'Consultant', level: 'C' },
  { id: 7, name: 'Associate', level: 'A' },
];

// Competencies
export const competencies = [
  { id: 1, name: 'Audit & Assurance' },
  { id: 2, name: 'Tax Services' },
  { id: 3, name: 'Advisory' },
  { id: 4, name: 'Technology Consulting' },
  { id: 5, name: 'Risk Management' },
  { id: 6, name: 'Forensic Services' },
  { id: 7, name: 'Transaction Advisory' },
];

// Rate matrix (grade-competency combinations)
export const rateMatrix = {
  'P-1': { billRate: 800, costRate: 400 },
  'P-2': { billRate: 850, costRate: 425 },
  'P-3': { billRate: 900, costRate: 450 },
  'P-4': { billRate: 950, costRate: 475 },
  'P-5': { billRate: 900, costRate: 450 },
  'P-6': { billRate: 850, costRate: 425 },
  'P-7': { billRate: 900, costRate: 450 },
  
  'D-1': { billRate: 650, costRate: 325 },
  'D-2': { billRate: 680, costRate: 340 },
  'D-3': { billRate: 700, costRate: 350 },
  'D-4': { billRate: 650, costRate: 325 },
  'D-5': { billRate: 680, costRate: 340 },
  'D-6': { billRate: 650, costRate: 325 },
  'D-7': { billRate: 700, costRate: 350 },
  
  'SM-1': { billRate: 480, costRate: 240 },
  'SM-2': { billRate: 500, costRate: 250 },
  'SM-3': { billRate: 520, costRate: 260 },
  'SM-4': { billRate: 480, costRate: 240 },
  'SM-5': { billRate: 500, costRate: 250 },
  'SM-6': { billRate: 480, costRate: 240 },
  'SM-7': { billRate: 520, costRate: 260 },
  
  'M-1': { billRate: 380, costRate: 190 },
  'M-2': { billRate: 400, costRate: 200 },
  'M-3': { billRate: 420, costRate: 210 },
  'M-4': { billRate: 380, costRate: 190 },
  'M-5': { billRate: 400, costRate: 200 },
  'M-6': { billRate: 380, costRate: 190 },
  'M-7': { billRate: 420, costRate: 210 },
  
  'SC-1': { billRate: 280, costRate: 140 },
  'SC-2': { billRate: 300, costRate: 150 },
  'SC-3': { billRate: 320, costRate: 160 },
  'SC-4': { billRate: 280, costRate: 140 },
  'SC-5': { billRate: 300, costRate: 150 },
  'SC-6': { billRate: 280, costRate: 140 },
  'SC-7': { billRate: 320, costRate: 160 },
  
  'C-1': { billRate: 180, costRate: 90 },
  'C-2': { billRate: 200, costRate: 100 },
  'C-3': { billRate: 220, costRate: 110 },
  'C-4': { billRate: 180, costRate: 90 },
  'C-5': { billRate: 200, costRate: 100 },
  'C-6': { billRate: 180, costRate: 90 },
  'C-7': { billRate: 220, costRate: 110 },
  
  'A-1': { billRate: 120, costRate: 60 },
  'A-2': { billRate: 130, costRate: 65 },
  'A-3': { billRate: 140, costRate: 70 },
  'A-4': { billRate: 120, costRate: 60 },
  'A-5': { billRate: 130, costRate: 65 },
  'A-6': { billRate: 120, costRate: 60 },
  'A-7': { billRate: 140, costRate: 70 },
};

// Recent pricing proposals for dashboard
export const recentPricings = [
  { 
    id: 'PR-2024-045', 
    opportunity: 'Digital Transformation', 
    client: 'Acme Corp', 
    value: '$850,000', 
    margin: '42%', 
    status: 'Approved', 
    partner: 'John Smith', 
    ratePerHour: '$185', 
    recoveryRate: '165%', 
    oppStatus: 'In Progress' 
  },
  { 
    id: 'PR-2024-044', 
    opportunity: 'Tax Advisory', 
    client: 'TechStart', 
    value: '$450,000', 
    margin: '38%', 
    status: 'Pending', 
    partner: 'Michael Chen', 
    ratePerHour: '$165', 
    recoveryRate: '140%', 
    oppStatus: 'Pending' 
  },
  { 
    id: 'PR-2024-043', 
    opportunity: 'Audit FY2024', 
    client: 'Global Industries', 
    value: '$1,200,000', 
    margin: '45%', 
    status: 'In Review', 
    partner: 'Sarah Johnson', 
    ratePerHour: '$220', 
    recoveryRate: '195%', 
    oppStatus: 'Approved' 
  },
];

// Pending approvals
export const pendingApprovals = [
  { id: 'PR-2024-044', client: 'TechStart Inc', margin: '38%', submitter: 'Sarah M.' },
  { id: 'PR-2024-042', client: 'InnovateTech', margin: '35%', submitter: 'Mike R.' },
  { id: 'PR-2024-041', client: 'DataFlow Ltd', margin: '40%', submitter: 'John D.' },
];